// Generated by CoffeeScript 1.7.1
window.onload = function() {
  var altp, alwd, getmin, i, icell, inum, ipage, ispace, iwidth, lwidth, onlod, oo, pd, setcell, url, _i;
  icell = $(window).innerWidth();
  iwidth = 200;
  ispace = 10;
  lwidth = iwidth + ispace;
  inum = 0;
  ipage = 0;
  alwd = Array();
  altp = Array();
  url = 'http://www.wookmark.com/api/json/popular?callback=?';
  pd = 2;
  oo = 300;
  onlod = function(p) {
    if (pd > 1) {
      pd = 0;
      $("#loading").show();
      $.getJSON(url, "page=" + p, function(data) {
        return $.each(data, function(index, obj) {
          var miheigh, minidex, omg;
          omg = $('<img/>');
          omg.attr("src", obj.preview);
          $("#container").append(omg);
          miheigh = iwidth / obj.width * obj.height;
          omg.css("width", iwidth);
          omg.css("height", miheigh);
          minidex = getmin();
          omg.css("left", alwd[minidex]);
          omg.css("top", altp[minidex]);
          return altp[minidex] = altp[minidex] + miheigh + 10;
        });
      });
      $("#loading").hide();
      pd = 2;
    }
    return console.log();
  };
  setcell = function() {
    inum = Math.floor(icell / lwidth);
    document.title = inum;
    $("#container").css("width", lwidth * inum - ispace);
    return console.log();
  };
  setcell();
  for (i = _i = 0; 0 <= inum ? _i < inum : _i > inum; i = 0 <= inum ? ++_i : --_i) {
    altp.push(0);
    alwd.push(i * lwidth);
  }
  console.log(alwd);
  onlod(ipage);
  console.log();
  getmin = function() {
    var index, mi, x, _j, _ref;
    mi = altp[0];
    index = 0;
    for (x = _j = 0, _ref = altp.length; 0 <= _ref ? _j < _ref : _j > _ref; x = 0 <= _ref ? ++_j : --_j) {
      if (mi > altp[x]) {
        mi = altp[x];
        index = x;
      }
    }
    return index;
  };
  $(window).on("scroll", function() {
    var hdex, hi;
    hi = $(window).innerHeight() + $(window).scrollTop();
    hdex = getmin();
    console.log($("#container").offset());
    if (altp[hdex] < hi - 50) {
      return onlod(ipage++);
    }
  });
  return console.log();
};
